#pragma once

#define VCOMTUNNEL_DEVICE_TYPE 0x8000
#define VCOMTUNNEL_PROTOCOL_MAJOR 1
#define VCOMTUNNEL_PROTOCOL_MINOR 0
#define VCOMTUNNEL_MAX_EVENT_BYTES 4096
#define VCOMTUNNEL_MAX_RX_BYTES 4096

#define IOCTL_VCOMTUNNEL_ATTACH CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_WAIT_EVENT CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_COMPLETE_EVENT CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_PUSH_RX CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_SET_CONNECTION_STATE CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_DETACH CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x806, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

typedef enum _VCOMTUNNEL_CONNECTION_STATE {
    VComTunnelDisconnected = 0,
    VComTunnelConnecting = 1,
    VComTunnelConnected = 2,
    VComTunnelFaulted = 3
} VCOMTUNNEL_CONNECTION_STATE;

typedef enum _VCOMTUNNEL_EVENT_TYPE {
    VComTunnelEventTxData = 1
} VCOMTUNNEL_EVENT_TYPE;

typedef struct _VCT_ATTACH_REQUEST {
    USHORT ProtocolMajor;
    USHORT ProtocolMinor;
    ULONG Flags;
    WCHAR ServiceInstanceId[64];
} VCT_ATTACH_REQUEST, *PVCT_ATTACH_REQUEST;

typedef struct _VCT_ATTACH_RESPONSE {
    USHORT ProtocolMajor;
    USHORT ProtocolMinor;
    ULONG DriverFlags;
    WCHAR PortName[32];
    ULONG MaxEventBytes;
    ULONG MaxRxBytes;
} VCT_ATTACH_RESPONSE, *PVCT_ATTACH_RESPONSE;

typedef struct _VCT_EVENT_HEADER {
    ULONG Size;
    ULONG RequestId;
    USHORT Type;
    USHORT Flags;
    ULONGLONG Sequence;
} VCT_EVENT_HEADER, *PVCT_EVENT_HEADER;

typedef struct _VCT_PUSH_RX {
    ULONG Flags;
    ULONG ByteCount;
    UCHAR Bytes[1];
} VCT_PUSH_RX, *PVCT_PUSH_RX;
