#pragma once

#define VCOMTUNNEL_DEVICE_TYPE 0x8000

#define IOCTL_VCOMTUNNEL_ATTACH CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_WAIT_EVENT CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_COMPLETE_EVENT CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_PUSH_RX CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_SET_CONNECTION_STATE CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_DETACH CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x806, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

typedef enum _VCOMTUNNEL_CONNECTION_STATE {
    VComTunnelDisconnected = 0,
    VComTunnelConnecting = 1,
    VComTunnelConnected = 2,
    VComTunnelFaulted = 3
} VCOMTUNNEL_CONNECTION_STATE;
