#pragma once

#define VCOMTUNNEL_DEVICE_TYPE 0x8000
#define VCOMTUNNEL_PROTOCOL_MAJOR 1
#define VCOMTUNNEL_PROTOCOL_MINOR 0
#define VCOMTUNNEL_MAX_EVENT_BYTES 4096
#define VCOMTUNNEL_MAX_RX_BYTES 4096

#define IOCTL_VCOMTUNNEL_ATTACH CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_WAIT_EVENT CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_COMPLETE_EVENT CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_PUSH_RX CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_SET_CONNECTION_STATE CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_DETACH CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x806, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_SET_MODEM_STATE CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x807, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VCOMTUNNEL_SET_LINE_STATE CTL_CODE(VCOMTUNNEL_DEVICE_TYPE, 0x808, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

typedef enum _VCOMTUNNEL_CONNECTION_STATE {
    VComTunnelDisconnected = 0,
    VComTunnelConnecting = 1,
    VComTunnelConnected = 2,
    VComTunnelFaulted = 3
} VCOMTUNNEL_CONNECTION_STATE;

typedef enum _VCOMTUNNEL_EVENT_TYPE {
    VComTunnelEventTxData = 1,
    VComTunnelEventSetBaudRate = 2,
    VComTunnelEventSetLineControl = 3,
    VComTunnelEventSetModemControl = 4,
    VComTunnelEventSetHandflow = 5,
    VComTunnelEventSetBreak = 6,
    VComTunnelEventPurge = 7
} VCOMTUNNEL_EVENT_TYPE;

typedef struct _VCT_ATTACH_REQUEST {
    USHORT ProtocolMajor;
    USHORT ProtocolMinor;
    ULONG Flags;
    WCHAR ServiceInstanceId[64];
} VCT_ATTACH_REQUEST, *PVCT_ATTACH_REQUEST;

typedef struct _VCT_ATTACH_RESPONSE {
    USHORT ProtocolMajor;
    USHORT ProtocolMinor;
    ULONG DriverFlags;
    WCHAR PortName[32];
    ULONG MaxEventBytes;
    ULONG MaxRxBytes;
} VCT_ATTACH_RESPONSE, *PVCT_ATTACH_RESPONSE;

typedef struct _VCT_EVENT_HEADER {
    ULONG Size;
    ULONG RequestId;
    USHORT Type;
    USHORT Flags;
    ULONGLONG Sequence;
} VCT_EVENT_HEADER, *PVCT_EVENT_HEADER;

typedef struct _VCT_PUSH_RX {
    ULONG Flags;
    ULONG ByteCount;
    UCHAR Bytes[1];
} VCT_PUSH_RX, *PVCT_PUSH_RX;

typedef struct _VCT_BAUD_RATE_EVENT {
    ULONG BaudRate;
} VCT_BAUD_RATE_EVENT, *PVCT_BAUD_RATE_EVENT;

typedef struct _VCT_LINE_CONTROL_EVENT {
    UCHAR StopBits;
    UCHAR Parity;
    UCHAR WordLength;
    UCHAR Reserved;
} VCT_LINE_CONTROL_EVENT, *PVCT_LINE_CONTROL_EVENT;

#define VCOMTUNNEL_MODEM_CONTROL_DTR 0x00000001
#define VCOMTUNNEL_MODEM_CONTROL_RTS 0x00000002

typedef struct _VCT_MODEM_CONTROL_EVENT {
    ULONG Mask;
    UCHAR Dtr;
    UCHAR Rts;
    UCHAR Reserved[2];
} VCT_MODEM_CONTROL_EVENT, *PVCT_MODEM_CONTROL_EVENT;

typedef struct _VCT_HANDFLOW_EVENT {
    ULONG ControlHandShake;
    ULONG FlowReplace;
} VCT_HANDFLOW_EVENT, *PVCT_HANDFLOW_EVENT;

typedef struct _VCT_BREAK_EVENT {
    UCHAR Enabled;
    UCHAR Reserved[3];
} VCT_BREAK_EVENT, *PVCT_BREAK_EVENT;

typedef struct _VCT_PURGE_EVENT {
    ULONG Mask;
} VCT_PURGE_EVENT, *PVCT_PURGE_EVENT;

typedef struct _VCT_MODEM_STATE {
    ULONG ModemStatus;
    ULONG EventMask;
} VCT_MODEM_STATE, *PVCT_MODEM_STATE;

typedef struct _VCT_LINE_STATE {
    ULONG Errors;
} VCT_LINE_STATE, *PVCT_LINE_STATE;
