using System.Globalization;
using VComTunnel.Core;

namespace VComTunnel.Gui;

public enum UiLanguage
{
    English,
    Chinese
}

internal static class GuiText
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Toolbar.Service"] = "Service",
        ["Toolbar.Mappings"] = "Mappings",
        ["Toolbar.ComPairs"] = "COM ports",
        ["Toolbar.Tools"] = "Tools",
        ["Toolbar.Language"] = "Language",
        ["Menu.Service"] = "Service",
        ["Menu.Mappings"] = "Mappings",
        ["Menu.ComPairs"] = "COM ports",
        ["Menu.Tools"] = "Tools",
        ["Menu.Language"] = "Language",
        ["Language.English"] = "English",
        ["Language.Chinese"] = "Chinese",
        ["Action.Refresh"] = "Refresh",
        ["Action.Add"] = "Add",
        ["Action.Save"] = "Save",
        ["Action.DeleteMapping"] = "Delete mapping",
        ["Action.Ports"] = "Ports",
        ["Action.CreatePair"] = "Create port...",
        ["Action.DeletePair"] = "Delete port...",
        ["Action.SetupDeps"] = "Setup deps",
        ["Action.ClearLogs"] = "Clear logs",
        ["Action.Start"] = "Start",
        ["Action.Stop"] = "Stop",
        ["Action.DeleteSelectedPair"] = "Delete port",
        ["Label.Status"] = "Status",
        ["Group.Mappings"] = "Tunnel mappings",
        ["Group.DependenciesPairs"] = "Diagnostics / COM ports",
        ["Group.Logs"] = "Logs",
        ["Column.Name"] = "Name",
        ["Column.Backend"] = "Backend",
        ["Column.VisibleCom"] = "Visible COM",
        ["Column.Backing"] = "Backing",
        ["Column.Host"] = "Host",
        ["Column.Port"] = "Port",
        ["Column.Auto"] = "Auto",
        ["Column.Restart"] = "Restart",
        ["Column.State"] = "State",
        ["Column.PairNumber"] = "#",
        ["Column.PortType"] = "Type",
        ["Column.PortA"] = "Port",
        ["Column.PortB"] = "Details",
        ["State.Stopped"] = "Stopped",
        ["State.Starting"] = "Starting",
        ["State.Running"] = "Running",
        ["State.Faulted"] = "Faulted",
        ["State.Unsupported"] = "Unsupported",
        ["Status.SelectMappingFirst"] = "Select a mapping first.",
        ["Status.SelectPairFirst"] = "Select a COM port first.",
        ["Status.ServiceChecking"] = "Service: checking...",
        ["Status.ServiceConnecting"] = "Service: connecting...",
        ["Status.ServiceOffline"] = "Service: offline",
        ["Status.ServiceStarting"] = "Service: starting...",
        ["Status.ServiceStartFailed"] = "Service: start failed",
        ["Status.ServiceConnected"] = "Service: connected, {0} mapping(s)",
        ["Status.Saved"] = "Saved.",
        ["Status.SaveFailed"] = "Save failed: {0}",
        ["Status.AutoSaved"] = "Changes saved.",
        ["Status.SavedMappings"] = "Saved {0} mapping(s).",
        ["Status.AddedMapping"] = "Added a mapping. Edit it, then Start when ready.",
        ["Status.DeletedMapping"] = "Deleted mapping {0}.",
        ["Status.DeletedMappingAndPort"] = "Deleted mapping {0}; COM port removal requested.",
        ["Status.DeletedMappingPortPending"] = "Deleted mapping {0}; COM port removal needs attention.",
        ["Status.DeleteMappingFailed"] = "Delete mapping failed: {0}",
        ["Status.FoundPairs"] = "Found {0} com0com pair(s).",
        ["Status.FoundPorts"] = "Found {0} com0com pair(s), {1} KMDF port(s).",
        ["Status.PortsFailed"] = "Ports failed: {0}",
        ["Status.KmdfUnsupported"] = "KMDF port management is available for installed test drivers.",
        ["Status.DependencyStateStale"] = "Service dependency state is stale. Close/reopen the GUI, then retry Start.",
        ["Status.ServiceDependencyCacheStale"] = "Service dependency cache is stale. Restart VComTunnel.Service or close/reopen the GUI.",
        ["Status.MappingNotFoundAfterSave"] = "{0}: mapping was not found after save. Select the row again and retry.",
        ["Status.ActionFailed"] = "{0} failed: {1}",
        ["Status.CreatePairFailed"] = "Create pair failed: {0}",
        ["Status.CreatePairEmptyPlan"] = "Create pair failed: empty setupc plan.",
        ["Status.DeletePairFailed"] = "Delete pair failed: {0}",
        ["Status.DeletePairEmptyPlan"] = "Delete pair failed: empty setupc plan.",
        ["Status.NoPairMatches"] = "No registered com0com pair matches {0} <-> {1}.",
        ["Status.WaitingPairRemoved"] = "Waiting for com0com pair {0} to be removed...",
        ["Status.DeletedPair"] = "Deleted com0com pair {0}.",
        ["Status.DeleteStillListed"] = "Delete launched, but pair {0} is still listed. Click Ports to inspect.",
        ["Status.PairRefreshFailed"] = "COM pair refresh failed: {0}",
        ["Status.WaitingPairAppear"] = "Waiting for com0com pair to appear...",
        ["Status.CreatedPairStarting"] = "Created com0com pair {0} <-> {1}. Starting...",
        ["Status.PairCreationNotDetected"] = "Pair creation was not detected. Click Ports to inspect, then Start again.",
        ["Status.StartCanceledMissingPair"] = "Start canceled: missing com0com pair {0} <-> {1}.",
        ["Status.KmdfPortExists"] = "{0} already exists.",
        ["Status.NoKmdfPortMatches"] = "No KMDF port matches {0}.",
        ["Status.WaitingKmdfPortAppear"] = "Waiting for KMDF port {0} to appear...",
        ["Status.CreatedKmdfPort"] = "Created KMDF port {0}.",
        ["Status.CreatedKmdfPortStarting"] = "Created KMDF port {0}. Starting...",
        ["Status.KmdfPortCreationNotDetected"] = "KMDF port {0} was not detected. Click Ports to inspect, then retry.",
        ["Status.StartCanceledMissingKmdfPort"] = "Start canceled: missing KMDF port {0}.",
        ["Status.WaitingKmdfPortRemoved"] = "Waiting for KMDF port {0} to be removed...",
        ["Status.DeletedKmdfPort"] = "Deleted KMDF port {0}.",
        ["Status.DeleteKmdfPortStillListed"] = "Delete launched, but KMDF port {0} is still listed. Click Ports to inspect.",
        ["Status.KmdfPortRefreshFailed"] = "KMDF port refresh failed: {0}",
        ["Status.KmdfCliNotFound"] = "Could not find VComTunnel.Cli.exe for elevated KMDF port management.",
        ["Status.LaunchKmdfCtl"] = "Launched KMDF {0} for {1}.",
        ["Status.LaunchKmdfCtlFailed"] = "Could not launch KMDF tool: {0}",
        ["Status.KmdfCtlOperationFailed"] = "KMDF tool failed: {0}",
        ["Status.KmdfCtlNoResult"] = "KMDF tool did not report a result. UAC may have been canceled, or the tool did not start.",
        ["Status.KmdfCtlNoPortAfterSuccess"] = "KMDF tool reported success, but the port state did not change yet: {0}",
        ["Status.DependenciesAlreadyReady"] = "Dependencies already ready.",
        ["Status.DependenciesReady"] = "Dependencies ready.",
        ["Status.DependencySetupFailed"] = "Dependency setup failed: {0}",
        ["Status.DependenciesDownloadedNeedInstall"] = "Dependencies prepared. com0com driver install is still required.",
        ["Status.DependencyRefreshTimeout"] = "Dependency refresh timed out. Click Refresh after the installer finishes.",
        ["Status.DependencyRefreshFailed"] = "Dependency refresh failed: {0}",
        ["Status.WaitingInstaller"] = "Waiting for com0com installer to finish...",
        ["Status.LaunchCom0comFailed"] = "Could not launch com0com installer: {0}",
        ["Status.LogsCleared"] = "Logs cleared.",
        ["Status.ClearLogsFailed"] = "Clear logs failed: {0}",
        ["Status.ClearLogsStatusFailed"] = "Clear logs failed: {0}",
        ["Status.LaunchSetupc"] = "Launched setupc: {0}",
        ["Prompt.CreatePair"] = "Create com0com pair {0} <-> {1}?\r\n\r\nThis launches setupc.exe with administrator approval.",
        ["Prompt.DeletePair"] = "Delete com0com pair {0}: {1} <-> {2}?\r\n\r\nStop tools using these ports before continuing.",
        ["Prompt.DeleteMapping"] = "Delete mapping {0} ({1})?\r\n\r\nNo matching VComTunnel COM port was found, so this only removes the tunnel mapping.",
        ["Prompt.DeleteMappingWithPort"] = "Delete mapping {0} ({1})?\r\n\r\nMatching COM port:\r\n{2}\r\n\r\nYes = delete the mapping and remove the COM port\r\nNo = delete the mapping only\r\nCancel = keep everything",
        ["Prompt.MissingPair"] = "The com0com pair {0} <-> {1} does not exist.\r\n\r\nCreate it now and then start this tunnel?",
        ["Prompt.CreateKmdfPort"] = "Create KMDF virtual serial port {0}?\r\n\r\nThis launches VComTunnel.Cli with administrator approval.",
        ["Prompt.DeleteKmdfPort"] = "Delete KMDF virtual serial port {0}?\r\n\r\nDevice instance:\r\n{1}\r\n\r\nStop tools using this port before continuing.",
        ["Prompt.MissingKmdfPort"] = "The KMDF virtual serial port {0} does not exist.\r\n\r\nCreate it now and then start this tunnel?",
        ["Prompt.LaunchCom0comInstaller"] = "com0com driver still needs an elevated installer run. Launch it now?",
        ["Title.ComPair"] = "VComTunnel COM pair",
        ["Title.KmdfPort"] = "VComTunnel KMDF port",
        ["Title.Mapping"] = "VComTunnel mapping",
        ["Title.DependencySetup"] = "VComTunnel dependency setup",
        ["Diag.NoDependencyReport"] = "No dependency report.",
        ["Diag.ComReady"] = "com0com/hub4com ready: {0}",
        ["Diag.KmdfReady"] = "KMDF install tooling ready: {0}",
        ["Diag.Found"] = "正常",
        ["Diag.Missing"] = "缺失",
        ["Diag.Fail"] = "失败",
        ["Diag.Partial"] = "不完整",
        ["Diag.ComPairsTitle"] = "com0com pairs",
        ["Diag.NoComPairs"] = "No com0com pairs found in Windows COM database.",
        ["Diag.PairLine"] = "{0} COM 对 {1}: {2} <-> {3}",
        ["Diag.DeleteCommand"] = "  delete: setupc.exe remove {0}",
        ["Diag.KmdfPortsTitle"] = "KMDF ports",
        ["Diag.NoKmdfPorts"] = "No VComTunnel KMDF ports found.",
        ["Diag.KmdfPortLine"] = "{0}: {1} {2}",
        ["Diag.KmdfControl"] = "control: {0}",
        ["Diag.KmdfDeleteCommand"] = "delete: vcomtunnelctl kmdf remove {0}",
        ["Diag.MissingA"] = "(missing A)",
        ["Diag.MissingB"] = "(missing B)",
        ["Diag.Offline"] = "VComTunnel.Service is not reachable at 127.0.0.1:44817.\r\n\r\n{0}\r\n\r\nClick Refresh to retry auto-start, or run VComTunnel.Service manually.",
        ["Diag.OfflineRetry"] = "VComTunnel.Service is not reachable at 127.0.0.1:44817. Click Refresh to retry auto-start, or run VComTunnel.Service manually.",
        ["Diag.ServiceNotFound"] = "Could not find VComTunnel.Service.exe near the GUI. Build the solution or start the service manually.",
        ["Diag.StartedButNotReady"] = "Started {0}, but 127.0.0.1:44817 did not become ready within 10 seconds.",
        ["Diag.StartupLog"] = "Startup log: {0}",
        ["Diag.LocalDetectorStale"] = "Local detector is ready, but the running service is not. The service process is likely stale.",
        ["Diag.LocalDetector"] = "Local detector:",
        ["Log.Gui"] = "gui",
        ["Log.Api"] = "api",
        ["Log.DependenciesReady"] = "Dependencies ready.",
        ["Log.DependenciesDownloadedNeedInstall"] = "Dependencies prepared. com0com driver install is still required.",
        ["Log.BackingChanged"] = "{0}: Backing cannot equal Visible; changed backing to {1}.",
        ["Log.KmdfBackingCleared"] = "{0}: KMDF mappings do not use Backing; cleared it.",
        ["Msg.Yes"] = "Yes",
        ["Msg.No"] = "No"
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["Toolbar.Service"] = "服务",
        ["Toolbar.Mappings"] = "映射",
        ["Toolbar.ComPairs"] = "COM 端口",
        ["Toolbar.Tools"] = "工具",
        ["Toolbar.Language"] = "语言",
        ["Menu.Service"] = "服务",
        ["Menu.Mappings"] = "映射",
        ["Menu.ComPairs"] = "COM 端口",
        ["Menu.Tools"] = "工具",
        ["Menu.Language"] = "语言",
        ["Language.English"] = "English",
        ["Language.Chinese"] = "中文",
        ["Action.Refresh"] = "刷新",
        ["Action.Add"] = "添加",
        ["Action.Save"] = "保存",
        ["Action.DeleteMapping"] = "删除映射",
        ["Action.Ports"] = "端口",
        ["Action.CreatePair"] = "创建端口...",
        ["Action.DeletePair"] = "删除端口...",
        ["Action.SetupDeps"] = "安装依赖",
        ["Action.ClearLogs"] = "清空日志",
        ["Action.Start"] = "启动",
        ["Action.Stop"] = "停止",
        ["Action.DeleteSelectedPair"] = "删除端口",
        ["Label.Status"] = "状态",
        ["Group.Mappings"] = "隧道映射",
        ["Group.DependenciesPairs"] = "诊断 / COM 端口",
        ["Group.Logs"] = "日志",
        ["Column.Name"] = "名称",
        ["Column.Backend"] = "后端",
        ["Column.VisibleCom"] = "可见 COM",
        ["Column.Backing"] = "后端口",
        ["Column.Host"] = "主机",
        ["Column.Port"] = "端口",
        ["Column.Auto"] = "自启",
        ["Column.Restart"] = "重启",
        ["Column.State"] = "状态",
        ["Column.PairNumber"] = "#",
        ["Column.PortType"] = "类型",
        ["Column.PortA"] = "端口",
        ["Column.PortB"] = "详情",
        ["State.Stopped"] = "已停止",
        ["State.Starting"] = "启动中",
        ["State.Running"] = "运行中",
        ["State.Faulted"] = "故障",
        ["State.Unsupported"] = "不支持",
        ["Status.SelectMappingFirst"] = "请先选择一条映射。",
        ["Status.SelectPairFirst"] = "请先选择一个 COM 端口。",
        ["Status.ServiceChecking"] = "服务：检查中...",
        ["Status.ServiceConnecting"] = "服务：连接中...",
        ["Status.ServiceOffline"] = "服务：离线",
        ["Status.ServiceStarting"] = "服务：启动中...",
        ["Status.ServiceStartFailed"] = "服务：启动失败",
        ["Status.ServiceConnected"] = "服务：已连接，{0} 条映射",
        ["Status.Saved"] = "已保存。",
        ["Status.SaveFailed"] = "保存失败：{0}",
        ["Status.AutoSaved"] = "改动已保存。",
        ["Status.SavedMappings"] = "已保存 {0} 条映射。",
        ["Status.AddedMapping"] = "已添加映射。编辑好后直接启动即可。",
        ["Status.DeletedMapping"] = "已删除映射 {0}。",
        ["Status.DeletedMappingAndPort"] = "已删除映射 {0}；已发起 COM 端口卸载。",
        ["Status.DeletedMappingPortPending"] = "已删除映射 {0}；COM 端口卸载需要检查。",
        ["Status.DeleteMappingFailed"] = "删除映射失败：{0}",
        ["Status.FoundPairs"] = "找到 {0} 个 com0com 对。",
        ["Status.FoundPorts"] = "找到 {0} 个 com0com 对，{1} 个 KMDF 端口。",
        ["Status.PortsFailed"] = "端口查询失败：{0}",
        ["Status.KmdfUnsupported"] = "KMDF 测试驱动已支持端口管理。",
        ["Status.DependencyStateStale"] = "服务依赖状态已过期。请关闭并重开 GUI 后再重试启动。",
        ["Status.ServiceDependencyCacheStale"] = "服务依赖缓存已过期。请重启 VComTunnel.Service 或关闭并重开 GUI。",
        ["Status.MappingNotFoundAfterSave"] = "{0}：保存后未找到该映射。请重新选择这一行后重试。",
        ["Status.ActionFailed"] = "{0}失败：{1}",
        ["Status.CreatePairFailed"] = "创建 COM 对失败：{0}",
        ["Status.CreatePairEmptyPlan"] = "创建 COM 对失败：setupc 计划为空。",
        ["Status.DeletePairFailed"] = "删除 COM 对失败：{0}",
        ["Status.DeletePairEmptyPlan"] = "删除 COM 对失败：setupc 计划为空。",
        ["Status.NoPairMatches"] = "没有找到匹配 {0} <-> {1} 的 com0com 对。",
        ["Status.WaitingPairRemoved"] = "正在等待 com0com 对 {0} 被删除...",
        ["Status.DeletedPair"] = "已删除 com0com 对 {0}。",
        ["Status.DeleteStillListed"] = "已发起删除，但 COM 对 {0} 仍在列表中。请点“端口”检查。",
        ["Status.PairRefreshFailed"] = "COM 对刷新失败：{0}",
        ["Status.WaitingPairAppear"] = "正在等待 com0com 对出现...",
        ["Status.CreatedPairStarting"] = "已创建 com0com 对 {0} <-> {1}，正在启动...",
        ["Status.PairCreationNotDetected"] = "未检测到 COM 对创建完成。请点“端口”检查后再启动。",
        ["Status.StartCanceledMissingPair"] = "启动已取消：缺少 com0com 对 {0} <-> {1}。",
        ["Status.KmdfPortExists"] = "{0} 已存在。",
        ["Status.NoKmdfPortMatches"] = "没有找到匹配 {0} 的 KMDF 端口。",
        ["Status.WaitingKmdfPortAppear"] = "正在等待 KMDF 端口 {0} 出现...",
        ["Status.CreatedKmdfPort"] = "已创建 KMDF 端口 {0}。",
        ["Status.CreatedKmdfPortStarting"] = "已创建 KMDF 端口 {0}，正在启动...",
        ["Status.KmdfPortCreationNotDetected"] = "未检测到 KMDF 端口 {0}。请点“端口”检查后重试。",
        ["Status.StartCanceledMissingKmdfPort"] = "启动已取消：缺少 KMDF 端口 {0}。",
        ["Status.WaitingKmdfPortRemoved"] = "正在等待 KMDF 端口 {0} 被删除...",
        ["Status.DeletedKmdfPort"] = "已删除 KMDF 端口 {0}。",
        ["Status.DeleteKmdfPortStillListed"] = "已发起删除，但 KMDF 端口 {0} 仍在列表中。请点“端口”检查。",
        ["Status.KmdfPortRefreshFailed"] = "KMDF 端口刷新失败：{0}",
        ["Status.KmdfCliNotFound"] = "没有找到用于提权管理 KMDF 端口的 VComTunnel.Cli.exe。",
        ["Status.LaunchKmdfCtl"] = "已启动 KMDF {0}：{1}。",
        ["Status.LaunchKmdfCtlFailed"] = "无法启动 KMDF 工具：{0}",
        ["Status.KmdfCtlOperationFailed"] = "KMDF 工具失败：{0}",
        ["Status.KmdfCtlNoResult"] = "KMDF 工具没有返回结果。可能取消了 UAC，或工具没有启动。",
        ["Status.KmdfCtlNoPortAfterSuccess"] = "KMDF 工具报告成功，但端口状态尚未变化：{0}",
        ["Status.DependenciesAlreadyReady"] = "依赖已就绪。",
        ["Status.DependenciesReady"] = "依赖已就绪。",
        ["Status.DependencySetupFailed"] = "依赖安装失败：{0}",
        ["Status.DependenciesDownloadedNeedInstall"] = "依赖包已准备好，仍需安装 com0com 驱动。",
        ["Status.DependencyRefreshTimeout"] = "依赖刷新超时。安装器完成后请点击“刷新”。",
        ["Status.DependencyRefreshFailed"] = "依赖刷新失败：{0}",
        ["Status.WaitingInstaller"] = "正在等待 com0com 安装器完成...",
        ["Status.LaunchCom0comFailed"] = "无法启动 com0com 安装器：{0}",
        ["Status.LogsCleared"] = "日志已清空。",
        ["Status.ClearLogsFailed"] = "清空日志失败：{0}",
        ["Status.ClearLogsStatusFailed"] = "清空日志失败：{0}",
        ["Status.LaunchSetupc"] = "已启动 setupc：{0}",
        ["Prompt.CreatePair"] = "创建 com0com 对 {0} <-> {1}？\r\n\r\n这会启动 setupc.exe 并请求管理员批准。",
        ["Prompt.DeletePair"] = "删除 com0com 对 {0}：{1} <-> {2}？\r\n\r\n继续前请先停止正在使用这些端口的工具。",
        ["Prompt.DeleteMapping"] = "删除映射 {0}（{1}）？\r\n\r\n没有找到匹配的 VComTunnel COM 端口，因此这里只会删除隧道映射。",
        ["Prompt.DeleteMappingWithPort"] = "删除映射 {0}（{1}）？\r\n\r\n匹配的 COM 端口：\r\n{2}\r\n\r\n是 = 删除映射并卸载 COM 端口\r\n否 = 只删除映射\r\n取消 = 保留全部",
        ["Prompt.MissingPair"] = "com0com 对 {0} <-> {1} 不存在。\r\n\r\n现在创建它并启动该隧道？",
        ["Prompt.CreateKmdfPort"] = "创建 KMDF 虚拟串口 {0}？\r\n\r\n这会启动 VComTunnel.Cli 并请求管理员批准。",
        ["Prompt.DeleteKmdfPort"] = "删除 KMDF 虚拟串口 {0}？\r\n\r\n设备实例：\r\n{1}\r\n\r\n继续前请先停止正在使用该端口的工具。",
        ["Prompt.MissingKmdfPort"] = "KMDF 虚拟串口 {0} 不存在。\r\n\r\n现在创建它并启动该隧道？",
        ["Prompt.LaunchCom0comInstaller"] = "com0com 驱动仍需要提权安装。现在启动安装器？",
        ["Title.ComPair"] = "VComTunnel COM 对",
        ["Title.KmdfPort"] = "VComTunnel KMDF 端口",
        ["Title.Mapping"] = "VComTunnel 映射",
        ["Title.DependencySetup"] = "VComTunnel 依赖安装",
        ["Diag.NoDependencyReport"] = "没有依赖报告。",
        ["Diag.ComReady"] = "com0com/hub4com 就绪：{0}",
        ["Diag.KmdfReady"] = "KMDF 安装工具就绪：{0}",
        ["Diag.Found"] = "OK",
        ["Diag.Missing"] = "MISS",
        ["Diag.Fail"] = "FAIL",
        ["Diag.Partial"] = "PARTIAL",
        ["Diag.ComPairsTitle"] = "com0com 对",
        ["Diag.NoComPairs"] = "Windows COM 数据库中没有找到 com0com 对。",
        ["Diag.PairLine"] = "{0} pair {1}: {2} <-> {3}",
        ["Diag.DeleteCommand"] = "  删除：setupc.exe remove {0}",
        ["Diag.KmdfPortsTitle"] = "KMDF 端口",
        ["Diag.NoKmdfPorts"] = "未找到 VComTunnel KMDF 端口。",
        ["Diag.KmdfPortLine"] = "{0}: {1} {2}",
        ["Diag.KmdfControl"] = "控制口：{0}",
        ["Diag.KmdfDeleteCommand"] = "删除：vcomtunnelctl kmdf remove {0}",
        ["Diag.MissingA"] = "（缺少 A）",
        ["Diag.MissingB"] = "（缺少 B）",
        ["Diag.Offline"] = "VComTunnel.Service 在 127.0.0.1:44817 不可达。\r\n\r\n{0}\r\n\r\n点击“刷新”可重试自动启动，或手动运行 VComTunnel.Service。",
        ["Diag.OfflineRetry"] = "VComTunnel.Service 在 127.0.0.1:44817 不可达。点击“刷新”可重试自动启动，或手动运行 VComTunnel.Service。",
        ["Diag.ServiceNotFound"] = "没有在 GUI 附近找到 VComTunnel.Service.exe。请构建解决方案或手动启动服务。",
        ["Diag.StartedButNotReady"] = "已启动 {0}，但 127.0.0.1:44817 在 10 秒内没有就绪。",
        ["Diag.StartupLog"] = "启动日志：{0}",
        ["Diag.LocalDetectorStale"] = "本地检测器已就绪，但运行中的服务未就绪。服务进程可能已过期。",
        ["Diag.LocalDetector"] = "本地检测器：",
        ["Log.Gui"] = "gui",
        ["Log.Api"] = "api",
        ["Log.DependenciesReady"] = "依赖已就绪。",
        ["Log.DependenciesDownloadedNeedInstall"] = "依赖包已准备好，仍需安装 com0com 驱动。",
        ["Log.BackingChanged"] = "{0}：后端口不能等于可见端口，已改为 {1}。",
        ["Log.KmdfBackingCleared"] = "{0}：KMDF 映射不使用后端口，已清空。",
        ["Msg.Yes"] = "是",
        ["Msg.No"] = "否"
    };

    public static UiLanguage DefaultLanguage =>
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("zh", StringComparison.OrdinalIgnoreCase)
            ? UiLanguage.Chinese
            : UiLanguage.English;

    public static string Get(UiLanguage language, string key)
    {
        var table = language == UiLanguage.Chinese ? Chinese : English;
        return table.TryGetValue(key, out var value) ? value : key;
    }

    public static string Format(UiLanguage language, string key, params object?[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, Get(language, key), args);
    }

    public static string State(UiLanguage language, TunnelRunState state)
    {
        return Get(language, $"State.{state}");
    }
}
